version: "3"

services:
  db:
    image: postgres:15.3
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite:/app
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
