# Generated by Django 4.1.6 on 2023-06-28 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 17, 47, 32, 512409, tzinfo=datetime.timezone.utc)),
        ),
    ]
